default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5432
  username: arquitetura
  password: 12345

development:
  <<: *default
  adapter: postgresql
  database: arquitetura_development
  port: 5432
  username: arquitetura
  password: 12345

test:
  <<: *default
  adapter: postgresql
  database: arquitetura_test
  port: 5432
  username: arquitetura
  password: 12345

production:
  <<: *default
  adapter: postgresql
  database: arquitetura_production
  port: 5432
  username: arquitetura
  password: 12345
